version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: aconchego-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: aconchego
    volumes:
      - mongodb_data:/data/db
    networks:
      - aconchego-network

volumes:
  mongodb_data:
    driver: local

networks:
  aconchego-network:
    driver: bridge
